#!/bin/sh

VER=$1
SUB=$2

rm -f repack_zip/emp/zImage
rm -f magisk_module/system/lib/modules/*.ko

if [ ! -d magisk_module/system ]; then
	mkdir magisk_module/system
	mkdir magisk_module/system/lib
	mkdir magisk_module/system/lib/modules
fi

cp out/arch/arm64/boot/Image.gz-dtb repack_zip/emp/zImage
cd out
find -name "*.ko" -exec mv {} ../magisk_module/system/lib/modules \;
cd ..
repack_zip/emp/strip --strip-unneeded magisk_module/system/lib/modules/*
mv magisk_module/system/lib/modules/wlan.ko magisk_module/system/lib/modules/qca_cld3_wlan.ko
###fake modules
touch magisk_module/system/lib/modules/bu520x1nvx.ko
touch magisk_module/system/lib/modules/fpc1145_platform.ko
touch magisk_module/system/lib/modules/ldo_vibrator.ko
touch magisk_module/system/lib/modules/mpq-adapter.ko
touch magisk_module/system/lib/modules/mpq-dmx-hw-plugin.ko
touch magisk_module/system/lib/modules/br_netfilter.ko
touch magisk_module/system/lib/modules/gspca_main.ko
touch magisk_module/system/lib/modules/kscl.ko
touch magisk_module/system/lib/modules/sim_detect.ko
touch magisk_module/system/lib/modules/rdbg.ko
touch magisk_module/system/lib/modules/msm_11ad_proxy.ko
touch magisk_module/system/lib/modules/sony_carillon_nfc.ko
touch magisk_module/system/lib/modules/test-iosched.ko
touch magisk_module/system/lib/modules/tspp.ko
touch magisk_module/system/lib/modules/ufs_test.ko
#touch magisk_module/system/lib/modules/texfat.ko

cd repack_zip
zip -r SO-04J_EMP_Kernel_Beta.zip *
mv SO-04J_EMP_Kernel_Beta.zip ../
cd ../magisk_module
zip -r SO-04J_EMP_Kernel_modules_magisk.zip *
mv SO-04J_EMP_Kernel_modules_magisk.zip ../
cd ..
echo "--------------------------------------------------"
echo "-              Repack      Completed             -"
echo "--------------------------------------------------"
echo "-              kernel  by rote66                 -"
echo "--------------------------------------------------"
echo "-Cutting Edge Aftermarket Sony Phone Technology-"
echo "--------------------------------------------------"
